require("core.plugin_config.gruvbox")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.hop")
require("core.plugin_config.lsp_config")
require("core.plugin_config.completions")
require("core.plugin_config.dressing")
-- require('core.plugin_config.neorg')
require("core.plugin_config.dap")
require("core.plugin_config.indent")
require("core.plugin_config.formatter")
require("core.plugin_config.jabs")
